#ifndef EXERCISE_CHARACTERFREQUENCYSTATISTICS_H
#define EXERCISE_CHARACTERFREQUENCYSTATISTICS_H

#define LENGTH 36
#define NUMLENGTH 10

void Count();

#endif //EXERCISE_CHARACTERFREQUENCYSTATISTICS_H